I have an python script using paramiko to connect to an ssh server debian host on AWS that I have already used before and I know that it works. But for some reason it would not connect now to this new AWS server. Debug logs from paramiko: I am able to connect successfully via putty to the same server. On another server, I have similar debug logs of a successful connection. The log show the same thing except that the final result is - Authentication (publickey) successful!