I'm trying to use PyCognito (AWS Cognito) to authenticate a user and an attached identity pool authenticated role to give permissions to the user to query an AppSync GraphQL endpoint. I'm getting a 401 Client Error: Unauthorized for url . Minimal Reproducible Example: raises the following exception. I have also added the following inline policy on the above authRole to try an blanket solve the permissions issue to no avail.